version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Paris
  assignees:
  - simonsampere
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
  - dependency-name: tox
    versions:
    - 3.21.3
