# coding: utf-8

"""
    Isogeo API v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.19.1.15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from .contact import Contact


# import models into model package
# from swagger_client.models.abilities import Abilities
# from swagger_client.models.application import Application
# from swagger_client.models.bbox import Bbox
# from swagger_client.models.catalog import Catalog
# from swagger_client.models.contact import Contact
# from swagger_client.models.inline_response200 import InlineResponse200
# from swagger_client.models.inline_response2001 import InlineResponse2001
# from swagger_client.models.keyword import Keyword
# from swagger_client.models.keyword_count import KeywordCount
# from swagger_client.models.license import License
# from swagger_client.models.resource import Resource
# from swagger_client.models.resource_condition import ResourceCondition
# from swagger_client.models.resource_conformity import ResourceConformity
# from swagger_client.models.resource_contact import ResourceContact
# from swagger_client.models.resource_event import ResourceEvent
# from swagger_client.models.resource_link import ResourceLink
# from swagger_client.models.service_layer import ServiceLayer
# from swagger_client.models.service_layer_titles import ServiceLayerTitles
# from swagger_client.models.service_operation import ServiceOperation
# from swagger_client.models.share import Share
# from swagger_client.models.specification import Specification
# from swagger_client.models.tags import Tags
# from swagger_client.models.thesaurus import Thesaurus
# from swagger_client.models.workgroup import Workgroup
